-- ===========================================================================
-- bronze.fs_seeded
--
-- GENERATED by scripts/generate_ddl.py from src/fs_ingest/schema.py.
-- DO NOT EDIT BY HAND — edit schema.py and re-run the generator, or the DDL
-- and the load job's schema will disagree.
--
-- Executed by scripts/push_to_bq.py's ensure_table() before every load;
-- CREATE TABLE IF NOT EXISTS, so it is idempotent.
--
-- TYPED, unlike every table in bronze_ingest. value is NUMERIC, is_bold is
-- BOOL, row_ord is INT64 — a deliberate divergence from the all-STRING
-- bronze contract, ruled in favour of the Group FS Ingestion Notes: footing
-- checks run at zero tolerance, and binary floating point would manufacture
-- breaks that are not in the document.
--
-- No source_file column, also per the Ingestion Notes — the table name
-- already identifies the document.
--
-- CLUSTER BY statement, not PARTITION BY: BigQuery partitions on DATE /
-- TIMESTAMP / INT64 only, so a STRING grouping key clusters.
--
-- Project  : aramco-finance-poc-c2a4
-- Dataset  : bronze          (location me-central2 - Dammam, IMMUTABLE)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS `aramco-finance-poc-c2a4.bronze.fs_seeded`
(
  statement STRING NOT NULL OPTIONS(description="The heading of the table this row was taken from, verbatim, e.g. 'Consolidated balance sheet' or 'Note 9 — Borrowings'. The grouping key of the whole model — cluster on it. NOTE THE EM DASH (U+2014, not a hyphen) in the note headings: equality filters must match the character exactly. Notes are values in this column rather than separate tables, so a note's internal arithmetic is checked by the same logic as a face statement, and adding a cash flow statement later is an insert rather than a schema change."),
  section STRING OPTIONS(description="Top-level grouping, e.g. 'Assets', 'Equity and liabilities', 'Operating costs'. NULL where the line sits outside any group — both for totals that sum across groups (Total assets) and for ordinary lines in no group (Finance costs). DERIVED, NOT PRINTED: the balance sheet never prints 'Assets' and the income statement prints no group headers at all, so the ranges are declared by label in configs/fs_*.json. This and subsection are the only interpreted columns in the table."),
  subsection STRING OPTIONS(description="Second level, balance sheet only: 'Non-current assets', 'Current assets', 'Equity', 'Non-current liabilities', 'Current liabilities'. Always NULL on the income statement and the notes — neither goes three deep. A group header row carries its own subsection, so filtering on one returns the group intact, header included; tell the header from a total by value IS NULL. DERIVED — see section."),
  label STRING NOT NULL OPTIONS(description="The line item description, verbatim, INCLUDING any note reference printed in the text ('Borrowings (Note 9)'). The parenthetical is deliberately not stripped or split into its own column: a wrong reference is a finding, it carries no arithmetic signal, and keeping the text is the only thing that makes it detectable at all. Never empty. NOT unique — 'Other assets and receivables' appears under both non-current and current assets."),
  column_label STRING OPTIONS(description="The column header, verbatim, e.g. 'Q1 2026', '31 Mar 2026'. DO NOT treat the second column as comparable across statements: the income statement compares to Q1 2025 (a prior-year quarter), the balance sheet to 31 Dec 2025 (a prior year end). Those are different dates — match on the literal string, never on column position. Note 9 is the exception: 'Non-current' / 'Current' / 'Total' are a breakdown axis rather than a period, which is why this column is not called period_label. Notes 5, 7 and 10 print 'SAR million' and are given the period of the face statement they support, so this column is NOT verbatim for those three."),
  value NUMERIC OPTIONS(description="The figure, as NUMERIC — never FLOAT64. Footing checks run at zero tolerance and binary floating point manufactures breaks that are not in the document. SIGNED AS PRESENTED: figures printed in parentheses are stored negative, so costs, treasury shares and accumulated depreciation are negative and every subtotal sums with a plain SUM and no per-section sign rules. NULL where the page prints no figure — the bold group headers on the balance sheet occupy a row and have empty cells. Every figure in both documents is SAR million; the unit is not a column because it never varies."),
  is_bold BOOL NOT NULL OPTIONS(description="Whether the row is set in bold on the page. A formatting fact, not an interpretation, which is why it belongs in bronze rather than an is_total column. It marks two things: group headers (bold, value NULL) and totals/subtotals (bold, value present). It earns its place because totals sit in the same table as their components, so an unguarded SUM(value) double-counts — and the label will not save you: most totals in these documents do not contain the word 'Total' (Operating income, Net income, Cost — closing, Net book value, External revenue)."),
  row_ord INT64 NOT NULL OPTIONS(description="Presentation order within a statement, from 1. Lets the statement be rendered back exactly as printed, and gives a stable way to point at a specific line. It is the line's position on the PAGE, not the row's position in this table, so it REPEATS once per column — Inventories appears twice at row_ord 11, once per period. The natural key is (statement, row_ord, column_label); BigQuery enforces no key, so ingest checks it.")
)
CLUSTER BY statement
OPTIONS(
  description="Saudi Aramco Group condensed consolidated financial statements for Q1 2026, the SEEDED-ERROR version, exactly as printed. 152 rows = income statement 19 lines x 2 periods + balance sheet 43 x 2 + Notes 5/7/10 7+5+7 x 1 column + Note 9 3 x 3 columns. Carries three deliberately planted defects: Total current assets prints 683,180 against components footing to 682,760; Revenue from contracts with customers prints 423,221 against 423,218; and non-current Borrowings cites (Note 5) where the borrowings note is Note 9 — a text-only defect with no arithmetic signal, detectable only because label keeps the reference verbatim. TYPED, not all-STRING: value NUMERIC, is_bold BOOL, row_ord INT64 — the only such tables in bronze, so that footing checks run at zero tolerance. No source_file column: the table name identifies the document. fs_clean and fs_seeded share this schema and have NO relationship — no join keys, no shared surrogate ids, and nothing presuming the two documents correspond row-for-row; the agent reads both and performs its own comparison. Ingest checks structure only and NEVER refuses to land on an arithmetic break — the breaks are the point. SYNTHETIC data."
);
