"""Regenerate sql/fs_clean.sql and sql/fs_seeded.sql from schema.py.

    python scripts/generate_ddl.py

The DDL is GENERATED, not hand-maintained — unlike bronze_ingest, where the
.sql files are the source of truth and the Python spec is kept in sync by
hand. Two reasons for the difference:

  - fs_clean and fs_seeded are the same schema twice. Hand-maintaining two
    near-identical 8-column DDLs with paragraph-length descriptions is an
    invitation for them to drift apart, and the whole point of the pair is
    that any difference between the tables comes from the DOCUMENTS.
  - The column descriptions are long, and they are product (Agent 6 reads
    them to pick columns). Keeping one copy in schema.py and projecting it
    into both the DDL and the load job means a correction lands everywhere.

The generated files ARE committed, so a reviewer can read the DDL in the PR
without running anything, and so `ensure_table()` has a file to execute.
Re-run this after any edit to schema.py and commit the result.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from fs_ingest.schema import (COLUMNS, DESCRIPTIONS,          # noqa: E402
                              REQUIRED, TABLES, TYPES)

PROJECT = "aramco-finance-poc-c2a4"

HEADER = """\
-- ===========================================================================
-- bronze.{name}
--
-- GENERATED by scripts/generate_ddl.py from src/fs_ingest/schema.py.
-- DO NOT EDIT BY HAND — edit schema.py and re-run the generator, or the DDL
-- and the load job's schema will disagree.
--
-- Executed by scripts/push_to_bq.py's ensure_table() before every load;
-- CREATE TABLE IF NOT EXISTS, so it is idempotent.
--
-- TYPED, unlike every table in bronze_ingest. value is NUMERIC, is_bold is
-- BOOL, row_ord is INT64 — a deliberate divergence from the all-STRING
-- bronze contract, ruled in favour of the Group FS Ingestion Notes: footing
-- checks run at zero tolerance, and binary floating point would manufacture
-- breaks that are not in the document.
--
-- No source_file column, also per the Ingestion Notes — the table name
-- already identifies the document.
--
-- CLUSTER BY statement, not PARTITION BY: BigQuery partitions on DATE /
-- TIMESTAMP / INT64 only, so a STRING grouping key clusters.
--
-- Project  : {project}
-- Dataset  : bronze          (location me-central2 - Dammam, IMMUTABLE)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS `{project}.bronze.{name}`
(
"""


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render(name: str) -> str:
    lines = []
    for column in COLUMNS:
        not_null = " NOT NULL" if column in REQUIRED else ""
        lines.append(
            f'  {column} {TYPES.get(column, "STRING")}{not_null} '
            f'OPTIONS(description="{escape(DESCRIPTIONS[column])}")')
    return (HEADER.format(name=name, project=PROJECT)
            + ",\n".join(lines)
            + "\n)\nCLUSTER BY statement\nOPTIONS(\n"
            + f'  description="{escape(TABLES[name])}"\n);\n')


def main() -> int:
    for name in TABLES:
        path = ROOT / "sql" / f"{name}.sql"
        path.parent.mkdir(parents=True, exist_ok=True)
        ddl = render(name)
        path.write_text(ddl, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}  ({len(ddl):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
